### ISSUE TITLE
[RFC] Discussion about the JSON test for drivers

### ISSUE THREAD

**Issue by stof** [minkphp/driver-testsuite#8]
A test using a JSON page was added a long time ago (in https://github.com/minkphp/Mink/commit/fb5dfa754e5dcf09faa8a1740f478404f13dd109).

However, this test asserts that the page content *contains* the JSON, not that it is exactly the JSON. And this is because in a real browser (Chromium through Selenium, but also PhantomJS), the actual page content looks like this:

```html
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"key1":"val1","key2":234,"key3":[1,2,3]}</pre></body></html>
```

The same is true for a plain-text page btw (JSON is treated as being plain-text here).

As browsers are meant to deal with HTML pages, I'm wondering whether this test actually makes sense. What do you think @aik099 @everzet ?

**Comment by aik099** [comment]
The Mink manipulates HTML of the page. Checking that it gets HTML as sent by Web Server via HTTP doesn't make any sense because nowadays driver underlying library (e.g. Zombie or Selenium) is modifying/making valid HTML anyway. The tests needs to ensure only, that whatever HTML we're getting we can manipulate.

So I'm OK with removing that test.

**Comment by stof** [comment]
@aik099 the question is whether we should request our drivers to support working with non-HTML responses. I would say no.

**Comment by aik099** [comment]
Since we previously rejected proposition to allow processing of XML document with Mink, then I agree, that non-HTML processing should not be supported.
